version: 2.1

orbs:
  gh-pages: sugarshin/gh-pages@0.0.6

jobs:
  build:
    docker:
      - image: cimg/node:16.0.0
    steps:
      - checkout
      - run: |
          cd AXIOM_Remote_3D_Visualizer && 
          npm install &&
          npx emsdk-checkout &&
          npx emsdk install latest &&
          npx emsdk activate latest &&
          npm run transpile_firmware &&
          npm run build
      - persist_to_workspace:
          root: AXIOM_Remote_3D_Visualizer
          paths: dist

  deploy-html:
    steps:
      - attach_workspace:
          at: ./
      - gh-pages/deploy:
          build-dir: dist/
          ssh-fingerprints: "81:d5:a7:f9:4f:00:79:f7:f5:c7:fa:75:1c:58:3b:4b"

workflows:
  version: 2
  build:
    jobs:
      - build:
        filters:
          branches:
            ignore:
              - gh-pages
      - deploy-html:
          requires:
            - build
          filters:
            branches:
              ignore:
                - gh-pages
