include(../../pico_sdk_import.cmake)

# target_sources(Drivers PRIVATE ili9341/ILI9341Display.cpp)
#add_library(Drivers INTERFACE ili9341/ILI9341Display.cpp)
#target_link_libraries(Drivers INTERFACE hardware_pio hardware_clocks)

#target_include_directories(Drivers  INTERFACE ${pico_sdk_SOURCE_DIR}/common)