#pragma once

enum class ScreenID
{
    MAIN,
    SETTINGS_MENU,
    FPS_SETTINGS,
    GAIN_SETTINGS,
    WHITE_BALANCE,
    SHUTTER_SPEED,
    DEBUG
};

enum class UIAction {
    OPEN_SETTINGS_MENU,
    OPEN_SHUTTER_SETTINGS,
    OPEN_WHITE_BALANCE_SETTINGS,
    OPEN_DEBUG_SCREEN,
    GO_TO_PREVIOUS_SCREEN
};
